// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mqMsg.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgToServer struct {
	GateSubject          string   `protobuf:"bytes,1,opt,name=GateSubject" json:"GateSubject,omitempty"`
	SessionID            int64    `protobuf:"varint,2,opt,name=SessionID" json:"SessionID,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgToServer) Reset()         { *m = MsgToServer{} }
func (m *MsgToServer) String() string { return proto.CompactTextString(m) }
func (*MsgToServer) ProtoMessage()    {}
func (*MsgToServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_mqMsg_8b7b50a195a6ecee, []int{0}
}
func (m *MsgToServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgToServer.Unmarshal(m, b)
}
func (m *MsgToServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgToServer.Marshal(b, m, deterministic)
}
func (dst *MsgToServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgToServer.Merge(dst, src)
}
func (m *MsgToServer) XXX_Size() int {
	return xxx_messageInfo_MsgToServer.Size(m)
}
func (m *MsgToServer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgToServer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgToServer proto.InternalMessageInfo

func (m *MsgToServer) GetGateSubject() string {
	if m != nil {
		return m.GateSubject
	}
	return ""
}

func (m *MsgToServer) GetSessionID() int64 {
	if m != nil {
		return m.SessionID
	}
	return 0
}

func (m *MsgToServer) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type MsgToGate struct {
	SessionID            int64    `protobuf:"varint,1,opt,name=SessionID" json:"SessionID,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=Tag" json:"Tag,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgToGate) Reset()         { *m = MsgToGate{} }
func (m *MsgToGate) String() string { return proto.CompactTextString(m) }
func (*MsgToGate) ProtoMessage()    {}
func (*MsgToGate) Descriptor() ([]byte, []int) {
	return fileDescriptor_mqMsg_8b7b50a195a6ecee, []int{1}
}
func (m *MsgToGate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgToGate.Unmarshal(m, b)
}
func (m *MsgToGate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgToGate.Marshal(b, m, deterministic)
}
func (dst *MsgToGate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgToGate.Merge(dst, src)
}
func (m *MsgToGate) XXX_Size() int {
	return xxx_messageInfo_MsgToGate.Size(m)
}
func (m *MsgToGate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgToGate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgToGate proto.InternalMessageInfo

func (m *MsgToGate) GetSessionID() int64 {
	if m != nil {
		return m.SessionID
	}
	return 0
}

func (m *MsgToGate) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *MsgToGate) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgToServer)(nil), "msg.MsgToServer")
	proto.RegisterType((*MsgToGate)(nil), "msg.MsgToGate")
}

func init() { proto.RegisterFile("mqMsg.proto", fileDescriptor_mqMsg_8b7b50a195a6ecee) }

var fileDescriptor_mqMsg_8b7b50a195a6ecee = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x2d, 0xf4, 0x2d,
	0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0x4a, 0xe4, 0xe2,
	0xf6, 0x2d, 0x4e, 0x0f, 0xc9, 0x0f, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0x12, 0x52, 0xe0, 0xe2, 0x76,
	0x4f, 0x2c, 0x49, 0x0d, 0x2e, 0x4d, 0xca, 0x4a, 0x4d, 0x2e, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0x42, 0x16, 0x12, 0x92, 0xe1, 0xe2, 0x0c, 0x4e, 0x2d, 0x2e, 0xce, 0xcc, 0xcf, 0xf3, 0x74,
	0x91, 0x60, 0x52, 0x60, 0xd4, 0x60, 0x0e, 0x42, 0x08, 0x08, 0x09, 0x71, 0xb1, 0xb8, 0x24, 0x96,
	0x24, 0x4a, 0x30, 0x2b, 0x30, 0x6a, 0xf0, 0x04, 0x81, 0xd9, 0x4a, 0xfe, 0x5c, 0x9c, 0x60, 0x2b,
	0x40, 0xa6, 0xa0, 0x6a, 0x67, 0x44, 0xd7, 0x2e, 0xc0, 0xc5, 0x1c, 0x92, 0x98, 0x0e, 0x36, 0x96,
	0x33, 0x08, 0xc4, 0xc4, 0x66, 0x60, 0x12, 0x1b, 0xd8, 0xfd, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xb3, 0x9a, 0x0d, 0x3e, 0xce, 0x00, 0x00, 0x00,
}
