// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg2server.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Msg2Server struct {
	GateSubject          string   `protobuf:"bytes,1,opt,name=GateSubject" json:"GateSubject,omitempty"`
	SessionID            int64    `protobuf:"varint,2,opt,name=SessionID" json:"SessionID,omitempty"`
	Msg                  []byte   `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg2Server) Reset()         { *m = Msg2Server{} }
func (m *Msg2Server) String() string { return proto.CompactTextString(m) }
func (*Msg2Server) ProtoMessage()    {}
func (*Msg2Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg2server_83bb6eb8b73483eb, []int{0}
}
func (m *Msg2Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg2Server.Unmarshal(m, b)
}
func (m *Msg2Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg2Server.Marshal(b, m, deterministic)
}
func (dst *Msg2Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg2Server.Merge(dst, src)
}
func (m *Msg2Server) XXX_Size() int {
	return xxx_messageInfo_Msg2Server.Size(m)
}
func (m *Msg2Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg2Server.DiscardUnknown(m)
}

var xxx_messageInfo_Msg2Server proto.InternalMessageInfo

func (m *Msg2Server) GetGateSubject() string {
	if m != nil {
		return m.GateSubject
	}
	return ""
}

func (m *Msg2Server) GetSessionID() int64 {
	if m != nil {
		return m.SessionID
	}
	return 0
}

func (m *Msg2Server) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*Msg2Server)(nil), "msg.msg2server")
}

func init() { proto.RegisterFile("msg2server.proto", fileDescriptor_msg2server_83bb6eb8b73483eb) }

var fileDescriptor_msg2server_83bb6eb8b73483eb = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x2d, 0x4e, 0x37,
	0x2a, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d,
	0x4e, 0x57, 0x8a, 0xe3, 0xe2, 0x42, 0x48, 0x08, 0x29, 0x70, 0x71, 0xbb, 0x27, 0x96, 0xa4, 0x06,
	0x97, 0x26, 0x65, 0xa5, 0x26, 0x97, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x21, 0x0b, 0x09,
	0xc9, 0x70, 0x71, 0x06, 0xa7, 0x16, 0x17, 0x67, 0xe6, 0xe7, 0x79, 0xba, 0x48, 0x30, 0x29, 0x30,
	0x6a, 0x30, 0x07, 0x21, 0x04, 0x84, 0x04, 0xb8, 0x40, 0x86, 0x4a, 0xb0, 0x28, 0x30, 0x6a, 0xf0,
	0x04, 0x81, 0x98, 0x49, 0x6c, 0x60, 0xbb, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x0b,
	0xd0, 0x2a, 0x7f, 0x00, 0x00, 0x00,
}
